eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8070

spring:
  application:
    name: schools
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:mem:schools
    driver-class-name: org.h2.Driver
    username: he
    password: he
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

application:
  config:
    students-url: http://localhost:8090/students
