eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090
spring:
 application:
   name: students
 config:
  import: optional:configserver:http://localhost:8888
 datasource:
   url: jdbc:h2:mem:students
   driver-class-name: org.h2.Driver
   username: sa
   password: as
 jpa:
   hibernate:
     ddl-auto: create
   database: h2
   database-platform: org.hibernate.dialect.H2Dialect
h2:
     console:
       enabled: true


